In [6]:
import csv, time
import numpy as np
from datetime import datetime
import pandas as pd
from io import StringIO

In [7]:
crime_2016 = pd.read_csv('Crimes_2016.csv', low_memory=False)
crime_2016.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10508593,HZ250410,5/3/2016 21:00,042XX W MADISON ST,1811,NARCOTICS,POSS: CANNABIS 30GMS OR LESS,SIDEWALK,True,False,...,28,26,18,1148220.0,1899677.0,2016,5/10/2016 15:56,41.880658,-87.731212,"(41.880658176, -87.731212135)"
1,10508594,HZ250385,5/3/2016 21:35,065XX S KEDVALE AVE,810,THEFT,OVER $500,APARTMENT,False,True,...,13,65,6,1149830.0,1860872.0,2016,5/10/2016 15:56,41.774141,-87.726307,"(41.77414081, -87.726307093)"
2,10508595,HZ250362,5/3/2016 14:45,045XX S DAMEN AVE,560,ASSAULT,SIMPLE,STREET,False,True,...,12,61,08A,1163662.0,1874660.0,2016,5/10/2016 15:56,41.811698,-87.675214,"(41.811697721, -87.675214316)"
3,10508597,HZ250202,5/3/2016 18:42,063XX S CLAREMONT AVE,486,BATTERY,DOMESTIC BATTERY SIMPLE,SIDEWALK,False,True,...,15,66,08B,1161829.0,1862607.0,2016,5/10/2016 15:56,41.778661,-87.682273,"(41.778661058, -87.68227253)"
4,10508598,HZ250298,5/3/2016 15:00,070XX S INDIANA AVE,320,ROBBERY,STRONGARM - NO WEAPON,SIDEWALK,False,False,...,6,69,3,1178808.0,1858478.0,2016,5/10/2016 15:56,41.766961,-87.620152,"(41.766961034, -87.620152116)"

In [9]:
crime_2016['ID'].count()

261004